// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://zbhaqyqlxzsjaayefpys.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InpiaGFxeXFseHpzamFheWVmcHlzIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQyMjY2NTUsImV4cCI6MjA1OTgwMjY1NX0.hyKUWRAnrxwk_XcF7FPNydX4v-iUDbVF8dBUO7HTFgo";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);